INSERT INTO DESIGNATION VALUES (1,'Director',1);
INSERT INTO DESIGNATION VALUES (2,'Manager',2);
INSERT INTO DESIGNATION VALUES (3,'Lead',3);
INSERT INTO DESIGNATION VALUES (4,'Developer',4);
INSERT INTO DESIGNATION VALUES (5,'DevOps',4);
INSERT INTO DESIGNATION VALUES (6,'QA',4);
INSERT INTO DESIGNATION VALUES (7,'Intern',5);

INSERT INTO EMPLOYEE VALUES (1,'Thor',-1,1);
INSERT INTO EMPLOYEE VALUES (2,'Iron Man',1,2);
INSERT INTO EMPLOYEE VALUES (3,'Hulk',1,3);
INSERT INTO EMPLOYEE VALUES (4,'Captain America',1,2);
INSERT INTO EMPLOYEE VALUES (5,'War Machine',2,6);
INSERT INTO EMPLOYEE VALUES (6,'Vision',2,5);
INSERT INTO EMPLOYEE VALUES (7,'Falcon',4,4);
INSERT INTO EMPLOYEE VALUES (8,'Ant Man',4,3);
INSERT INTO EMPLOYEE VALUES (9,'Spider Man',2,7);
INSERT INTO EMPLOYEE VALUES (10,'Black Widow',3,4)