apiVersion: v1
kind: Service
metadata:
  name: ems-service
  labels:
    app: ems-app
    tier: backend
spec:
  ports:
    - port: 8080
      name: http
  type : NodePort
  selector:
    app: ems-app
    tier: backend



